### ISSUE TITLE
File > New

### ISSUE THREAD

**Issue by ghost** [NGLEmp/NGLEmp#1]
I'm not sure if this is being caused by NGLEmp or the 'Home Screen replacement from CC 2017', but either way I figured you needed to be made aware of it.

For some reason, 'Save Document Preset' is open by default, which led me to being very confused at first as to how to make a new document. Every time you go to File > New, you have to click the Close button in the top right, like so:

![2019-05-25 07 14 34 2](https://user-images.githubusercontent.com/37132025/58369244-384d0080-7ebd-11e9-9419-7ce79ae81214.gif)

Anyway it annoys me greatly, so if you know of any solution to this, let me know!

<br/><br/>

P.S. The description states `Search web for alternative Home Screen. There are some.`, but I was not able to find a single one. Could you give me some search terms that work, or maybe link me one? If you're worried about there being a record of it, you could use https://cryptopaste.org/ and set Expiration to 'Burn after reading', which will delete it after it's viewed.

**Comment by NGLEmp** [comment]
@Aidolii this could help:

Adobe 2019/2020 **Home Screen FIX** `v2.7`

### What's new

1. Update CCXP `3.0.1` For `2019`
2. Added CCXP `3.0.4` For `2020`

### Download
[.](https://cryptopaste.org/dGOzvlbw)

### Passwwwwword:
[.](WorldComYmA2muZ9hzHSdAOmPssLpttOBG28LAWG1aysWrD/7cEws33uxMZ+Oe2+)

**Comment by vinayvardhan999** [comment]
Password, Error 404

**Comment by NGLEmp** [comment]
> Password, Error 404

Sure. It's like a simple quest. You need to analyse link and extract password from it.

**Comment by Aidolii** [comment]
> > Password, Error 404
> 
> Sure. It's like a simple quest. You need to analyse link and extract password from it.

I think he was confused because github automatically added `https://github.com/NGLEmp/NGLEmp/issues/` to the front of the password link.

**Comment by MestreTM** [comment]
@NGLEmp could send again, the link has expired
