### ISSUE TITLE
Does not work with Photoshop for Windows ARM64 version

### ISSUE THREAD

**Issue by TGSAN** [NGLEmp/NGLEmp#11]
This does not work with Photoshop Windows ARM64 version. (Adobe Photoshop 2021 22.5)
no NGLEmp in `Help -> About Plug-ins`, after copy `NGLEmp.8bx` and `painter.cfg` to `%ProgramFiles%\Adobe\Adobe Photoshop 2021\Required\Plug-ins\Extensions`

**Comment by upiter** [comment]
ARM64 is not supported.
The only supported platform is x86-64.
[Added](https://github.com/NGLEmp/NGLEmp/commit/1e73d92c64b403be12ca140c68c7dab8b7b0ba0e) notice to [README](https://github.com/NGLEmp/NGLEmp/blob/master/README.md) about x86-64.
