### ISSUE TITLE
Does not work with current PS v23.2

### ISSUE THREAD

**Issue by update-freak** [NGLEmp/NGLEmp#15]
Does not work with current PS v23.2

**Comment by scmyyc** [comment]
Yes, I have the same problem

**Comment by CrypticCus** [comment]
same here

**Comment by AdKiller** [comment]
Same, I hope this is not the end of NGLEmp

**Comment by Shudushi** [comment]
+1

**Comment by MrPropre** [comment]
Same

**Comment by MolinariRodrigo** [comment]
same

any way to get back to version 23.1?

**Comment by upiter** [comment]
Take it easy.

**Comment by CrypticCus** [comment]
I hope he/she is alive

**Comment by Shudushi** [comment]
Because nothing goes on here, I had to look for an alternative. 😢

**Comment by CrypticCus** [comment]
soo its been more than 1 month

**Comment by update-freak** [comment]
any news on that.
As far I am know Neural filters doesn't work with GenP.
So a new update would be great!

**Comment by ValZapod** [comment]
> As far I am know Neural filters doesn't work with GenP.

They do if you will also install this plugin.

**Comment by upiter** [comment]
[Updated](https://github.com/NGLEmp/NGLEmp/commits/master) to support latest Adobe Photoshop `2022`: `23.3`
492a0fd3e41fa817430dbb91c64a9808f5e9d457
