### ISSUE TITLE
NGLEmp 0.8.2.0 works well in Ps 23.3.0, but doesn't work in Ps 23.3.1

### ISSUE THREAD

**Issue by wesle9977** [NGLEmp/NGLEmp#17]
0.8.2.0 does not work at 23.3.1 :(

**Comment by upiter** [comment]
[Updated](https://github.com/NGLEmp/NGLEmp/commits/master) to support latest Adobe Photoshop `2022`: `23.3.1`
e84318abc7d64c16a06d789883409965e307b46d
