### ISSUE TITLE
I can't find NGLEmp.8bx in the lastest release

### ISSUE THREAD

**Issue by Skywalker95241** [NGLEmp/NGLEmp#21]
Sorry I'm new here. I Downloaded the latest version but I can't find the NGLEmp.8bx to put in the directory. Thanks

**Comment by upiter** [comment]
Hi ~Luc~ @Skywalker95241 and welcome to this dangerous, unfriendly and uncomfortable place.

It's sad that you had time only to write new issue without finding more time to carefully investigate [existing documentation](https://github.com/NGLEmp/NGLEmp/blob/master/DOWNLOAD.md#download).

It's highly recommended to examine [closed issues](https://github.com/NGLEmp/NGLEmp/issues?q=is%3Aissue+is%3Aclosed) also. And may be you'll be awarded by someone else' [recommendation](https://github.com/NGLEmp/NGLEmp/issues/19#issuecomment-1146513625).
