### ISSUE TITLE
"New > Create" does not work with version 21.1.0

### ISSUE THREAD

**Issue by update-freak** [NGLEmp/NGLEmp#5]
If you click on "New" and then on "Create" nothing happens (and the dialog does not disappear)?
With the previous version 21.0.3, this still works without problems.
I don't know if that's a problem with NGLEmp or with Photoshop itself.

**Comment by Tenns** [comment]
i have the exact same problem!

**Comment by ViperCode7** [comment]
In Photoshop? Cause that's the only one with ver 21.
Anyway, when asking for help it's advised to formulate your issue with sufficient information. Not whatever it is that you posted.

In PS I haveNew and OK, not create. And it works properly. Tested it on PS 21.1.1.121 x64.

**Comment by Tenns** [comment]
Wow such passive aggressiveness.

Obviously in Photoshop ? You wanna use this plugin in your toaster ? and it's not because you can't reproduce the same issue you have to be such an insufferable git.

It didn't work on multiples versions of v21 for me.

**Comment by ViperCode7** [comment]
Well, probably it doesn't work for you 'cause you're an asshole? I guess...

Anyway just I came from a license PS 2017 and I just met these new changes, which were not present in it. My post was a suggestion in getting help faster, and the plugin works properly, meaning, in your incommensurable wisdom, you f-ed up.

PS: my toaster is an 8 core with 16GB RAM and a 512GB SSD, but whatever floats your boat, snowflake.

**Comment by Tenns** [comment]
hey dude you seem like the type that loves to show how tough he is.

your toaster cannot be a PC coz you cant install a plugin on hardware but hey, at least you tried. 

And can I just say you, you trying to boas my your config is pretty funny coz it's seems like a MacBook to me, you "snowflake"? you are so edgy lmao, probably loves to use cuck as well.

And by the way, can you try to make sense, I can't decipher the meaning of this : "Anyway just I came from a licensed PS 2017 and I just met these new changes, which were not present in it."

**Comment by update-freak** [comment]
Work around: Edit -> Preferences -> General -> Use the old "New Document" user interface

**Comment by 0lm** [comment]
> 
> 
> Work around: Edit -> Preferences -> General -> Use the old "New Document" user interface

thanks, that worked! but unfortunately "save under" isnt working either and maybe also some aother stuff i didnt test yet. i guess for now best option is to get a working version of photoshop instead of the newest

**Comment by ValZapod** [comment]
You need to install old version and update using that plugin intact. On clean system. That is at least how it is here. Everything works))

**Comment by ValZapod** [comment]
You need to install old version and update using that plugin intact. On clean system. That is at least how it is here. Everything works))

**Comment by a1waysbeta** [comment]
> thanks, that worked! but unfortunately "save under" isnt working either and maybe also some aother stuff i didnt test yet. 

You should first open a document or picture, and then set the Preferences, save will work.

**Comment by a1waysbeta** [comment]
1. Install Adobe Photoshop CC  2020 （21.2.0） using CCMaker
2. Install NGLEmp
3. Install Adobe_2019_2020_Home_Screen_FIX_v3.4.0
4. New 0 byte placeholder program
if (WinVer < 10 || (WinVer == 10 && BuildVersion == 10240))
\CommonProgramFiles(x86)\Adobe\OOBE\PDApp\IPC\AdobeIPCBroker.exe
if (WinVer >= 10 && BuildVersion > 10240)
\CommonProgramFiles(x86)%\Adobe\Adobe Desktop Common\IPCBox\AdobeIPCBroker.exe
5. Everything works.
![02](https://user-images.githubusercontent.com/11453148/85811206-06792e00-b790-11ea-801e-74061caea9b2.gif)
