### ISSUE TITLE
Does not work with version 22

### ISSUE THREAD

**Issue by update-freak** [NGLEmp/NGLEmp#6]
This does not work with Adobe Photoshop with version 22

**Comment by NGLEmp** [comment]
Updated in [ed78bfe](https://github.com/NGLEmp/NGLEmp/commit/ed78bfea735aa2089d92ef51ef6617620c73c322#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).

See [README](https://github.com/NGLEmp/NGLEmp/blob/master/README.md#download).
