### ISSUE TITLE
download link is 0.6.9

### ISSUE THREAD

**Issue by fisherwise** [NGLEmp/NGLEmp#7]

**Comment by NGLEmp** [comment]
Updated in [ed78bfe](https://github.com/NGLEmp/NGLEmp/commit/ed78bfea735aa2089d92ef51ef6617620c73c322#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).

See [README](https://github.com/NGLEmp/NGLEmp/blob/master/README.md#download)
